LogFormat "{ \"host\":\"%v\", \"port\":\"%p\", \"remote_ip\":\"%a\", \"user\":\"%u\", \"time\":\"%{%Y-%m-%dT%H:%M:%S%z}t\", \"method\":\"%m\", \"uri\":\"%U\", \"protocol\":\"%H\", \"status\":\"%>s\", \"bytes\":%O, \"referer\":\"%{Referer}i\", \"user_agent\":\"%{User-Agent}i\", \"response_time_us\":%D }" json
ErrorLogFormat "{ \"time\":\"%{cu}t\", \"level\":\"%l\", \"module\":\"%m\", \"pid\":%P, \"message\":\"%M\" }"

<VirtualHost *:80>

        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html/web

        ErrorLog /dev/stderr
        SetEnvif Request_URI "^/lb_htalth_check/htalth_check.html$" nolog
        CustomLog /dev/stdout json env=!nolog

        Header always unset X-Powered-By
        Header always set X-Generator Drupal

        RewriteEngine On
        RewriteRule ^/web/?$ / [R=302,L]
        RewriteRule ^/web/(.*)$ /$1 [R=302,L]

        <Directory "/var/www/html/web">
            Options All -Indexes
            AllowOverride All
            Require all granted
        </Directory>

        Alias /lb_htalth_check /var/www/lb_htalth_check
        <Directory "/var/www/lb_htalth_check">
            Options All -Indexes
            AllowOverride All
            Require all granted
        </Directory>

</VirtualHost>
