Define ForbiddenExtensions "(?i:\
ade|asa|ashx|asmx|asp|bas|bat|cdx|cer|chm|class|cmd|cnt|com|config|cpl|crt|csh|dll|fxp|\
gadget|grp|hlp|hpj|htr|htw|ida|idc|idq|ins|isp|its|jse|json|ksh|lnk|mad|maf|mag|mam|maq|\
mar|mas|mat|mau|mav|maw|mcf|mda|mdb|mde|mdt|mdw|mdz|ms-one-stub|msc|msh|msh1|msh1xml|msh2|\
msh2xml|mshxml|msi|msp|mst|ops|pcd|pif|pl|prf|prg|printer|ps1|ps1xml|ps2|ps2xml|psc1|psc2|\
pst|reg|rem|scf|scr|sct|shb|shs|shtm|shtml|soap|stm|svc|vb|vbe|vbs|vsix|ws|wsc|wsf|wsh|xamlx|\
exe\
)"